"""SAGE-PRO Demo: Full Pipeline Reasoning Trajectory.

Runs in two modes:
  --mock   : Simulates the entire AODE pipeline locally (no GPU, no deps).
  (default): Calls the live LangGraph pipeline against co-resident vLLM backends.
"""
import asyncio
import argparse
import sys
import time
import os
from pathlib import Path

# Force UTF-8 output on Windows
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")


# ── Mock-mode helpers (zero external deps) ──────────────────────────────

MOCK_LRU_CODE = '''\
"""Thread-safe LRU Cache with TTL and async eviction — hardened by SAGE-PRO."""
import asyncio
import threading
import time
from collections import OrderedDict
from typing import Any, Optional


class AsyncTTLCache:
    """A thread-safe LRU cache with per-key TTL and background async eviction.

    Design rationale (SAGE-PRO Architect):
        - OrderedDict gives O(1) move-to-end for LRU ordering.
        - A dedicated asyncio task performs periodic sweeps instead of
          checking expiry on every read (amortised cost).
        - threading.Lock protects the dict so sync callers are safe too.
    """

    def __init__(self, maxsize: int = 128, default_ttl: float = 60.0,
                 eviction_interval: float = 5.0) -> None:
        self._maxsize = maxsize
        self._default_ttl = default_ttl
        self._eviction_interval = eviction_interval
        self._store: OrderedDict[str, tuple[Any, float]] = OrderedDict()
        self._lock = threading.Lock()
        self._eviction_task: Optional[asyncio.Task[None]] = None

    # ── public API ───────────────────────────────────────────────────

    def get(self, key: str) -> Optional[Any]:
        """Return value for *key* or None if missing / expired."""
        with self._lock:
            if key not in self._store:
                return None
            value, expires = self._store[key]
            if time.monotonic() > expires:
                del self._store[key]
                return None
            self._store.move_to_end(key)
            return value

    def put(self, key: str, value: Any, ttl: Optional[float] = None) -> None:
        """Insert or update *key*.  Evicts LRU entry when full."""
        ttl = ttl if ttl is not None else self._default_ttl
        with self._lock:
            if key in self._store:
                self._store.move_to_end(key)
            self._store[key] = (value, time.monotonic() + ttl)
            if len(self._store) > self._maxsize:
                self._store.popitem(last=False)

    @property
    def size(self) -> int:
        return len(self._store)

    # ── async eviction ───────────────────────────────────────────────

    async def start_eviction(self) -> None:
        """Launch the background eviction loop."""
        self._eviction_task = asyncio.create_task(self._evict_loop())

    async def stop_eviction(self) -> None:
        if self._eviction_task:
            self._eviction_task.cancel()
            try:
                await self._eviction_task
            except asyncio.CancelledError:
                pass

    async def _evict_loop(self) -> None:
        while True:
            await asyncio.sleep(self._eviction_interval)
            now = time.monotonic()
            with self._lock:
                expired = [k for k, (_, exp) in self._store.items() if now > exp]
                for k in expired:
                    del self._store[k]
'''

MOCK_TEST_CODE = '''\
"""Tests for AsyncTTLCache — generated by SAGE-PRO Red-Team Ensemble."""
import asyncio
import time
import threading
import pytest

from lru_async import AsyncTTLCache


class TestBasicOperations:
    def test_put_and_get(self):
        cache = AsyncTTLCache(maxsize=8)
        cache.put("a", 1)
        assert cache.get("a") == 1

    def test_missing_key_returns_none(self):
        cache = AsyncTTLCache()
        assert cache.get("nonexistent") is None

    def test_lru_eviction(self):
        cache = AsyncTTLCache(maxsize=2)
        cache.put("a", 1)
        cache.put("b", 2)
        cache.put("c", 3)  # evicts "a"
        assert cache.get("a") is None
        assert cache.get("b") == 2

    def test_update_moves_to_end(self):
        cache = AsyncTTLCache(maxsize=2)
        cache.put("a", 1)
        cache.put("b", 2)
        cache.put("a", 10)   # refresh "a"
        cache.put("c", 3)    # evicts "b" (oldest)
        assert cache.get("a") == 10
        assert cache.get("b") is None


class TestTTLExpiry:
    def test_expired_key_returns_none(self):
        cache = AsyncTTLCache(default_ttl=0.05)
        cache.put("x", 42)
        time.sleep(0.1)
        assert cache.get("x") is None

    def test_custom_ttl(self):
        cache = AsyncTTLCache(default_ttl=10.0)
        cache.put("short", 1, ttl=0.05)
        time.sleep(0.1)
        assert cache.get("short") is None


class TestThreadSafety:
    def test_concurrent_writes(self):
        cache = AsyncTTLCache(maxsize=1000)
        errors = []

        def writer(prefix: str):
            try:
                for i in range(200):
                    cache.put(f"{prefix}_{i}", i)
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=writer, args=(f"t{t}",)) for t in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert not errors
        assert cache.size <= 1000


class TestAsyncEviction:
    @pytest.mark.asyncio
    async def test_background_eviction(self):
        cache = AsyncTTLCache(maxsize=100, default_ttl=0.05, eviction_interval=0.1)
        cache.put("die", 1)
        await cache.start_eviction()
        await asyncio.sleep(0.3)
        assert cache.get("die") is None
        await cache.stop_eviction()
'''

MOCK_BENCHMARKS = """\
# SAGE-PRO Benchmarks -- AsyncTTLCache

| Metric              | Value        |
|---------------------|--------------|
| Throughput (ops/s)  | 1,247,000    |
| p50 latency (us)    | 0.8          |
| p99 latency (us)    | 4.2          |
| Eviction latency    | 42 us        |
| Thread-safety       | PASS         |
| TTL correctness     | PASS         |
| Coverage            | 94.2%        |
"""


def _print_slow(msg: str, delay: float = 0.04) -> None:
    """Print with a small delay to simulate real-time streaming."""
    print(msg, flush=True)
    time.sleep(delay)


async def run_mock_demo(task: str) -> None:
    """Simulate the full AODE reasoning trajectory without any backend."""
    output_dir = Path("demo_output")
    output_dir.mkdir(exist_ok=True)

    _print_slow("")
    _print_slow("+--------------------------------------------------------------+")
    _print_slow("|     SAGE-PRO  Reasoning Engine  v1.0.0                       |")
    _print_slow("|     Adversarial Orthogonal Divergence Engine                 |")
    _print_slow("+--------------------------------------------------------------+")
    _print_slow("")
    _print_slow(f"  Task: {task}")
    _print_slow("-" * 62)

    # Phase 1 -- Ingest & Route
    _print_slow("[ROUTE]   Embedding task via bge-small-en-v1.5 ...")
    time.sleep(0.3)
    _print_slow("          FAISS HNSW index: 384-dim, 32 neighbors")
    _print_slow("          Persistent Homology: B1=2, B2=0  ->  2 topological voids detected")
    _print_slow("          Routed to void: 'Concurrency primitives in memory-constrained contexts'")
    _print_slow("")

    # Phase 2 -- VRAM Ledger
    _print_slow("[VRAM]    +-- Co-resident VRAM Ledger (MI300X 192 GB) ---------+")
    _print_slow("          |  Architect   Qwen2.5-32B-AWQ       22.4 GB        |")
    _print_slow("          |  Implementer DeepSeek-V2-Lite-AWQ  13.8 GB        |")
    _print_slow("          |  Synthesizer Qwen2.5-72B-AWQ       45.2 GB        |")
    _print_slow("          |  Red-Team-A  DeepSeek-V2-Lite      13.8 GB        |")
    _print_slow("          |  Red-Team-B  StarCoder2-15B-FP16   30.0 GB        |")
    _print_slow("          |  KV-cache + activations            59.0 GB        |")
    _print_slow("          |----------------------------------------------------")
    _print_slow("          |  TOTAL                            184.2 GB        |")
    _print_slow("          |  H100 cap                          80.0 GB  FAIL  |")
    _print_slow("          |  MI300X cap                       192.0 GB  OK    |")
    _print_slow("          +----------------------------------------------------+")
    _print_slow("")

    # Phase 3 -- Architect
    _print_slow("[ARCH]    Generating architectural spec ...")
    time.sleep(0.4)
    _print_slow("          Design: 'OrderedDict + threading.Lock + asyncio eviction task'")
    _print_slow("          Torsion suffix applied: 'Consider async-first with sync adapter'")
    _print_slow("")

    # Phase 4 -- Parallel Implementation
    _print_slow("[IMPL]    Launching parallel branches (asyncio.gather) ...")
    time.sleep(0.5)
    _print_slow("          Branch ABC (Design-first):  -> async-native with Lock")
    _print_slow("          Branch ACB (Threat-first):   -> sync-safe with async eviction bolt-on")
    _print_slow("")

    # Phase 5 -- Red-Team Pre-Attack
    _print_slow("[RED]     Red-Team Ensemble pre-attack ...")
    time.sleep(0.3)
    _print_slow("          DeepSeek-V2-Lite: Generated 6 adversarial tests (deadlock, race)")
    _print_slow("          StarCoder2-15B:   Generated 4 property-based tests (Hypothesis)")
    _print_slow("          Merged (AST dedup): 8 unique tests")
    _print_slow("")

    # Phase 6 -- Synthesis
    _print_slow("[SYNTH]   Lie Bracket [ABC, ACB] divergence = 0.142")
    _print_slow("          Signal strength: MODERATE -- branches explored distinct manifolds")
    time.sleep(0.3)
    _print_slow("          Synthesizer merging best-of-both into hardened artifact ...")
    _print_slow("")

    # Phase 7 -- Nash Crucible
    for cycle in range(1, 4):
        _print_slow(f"[CYCLE {cycle}] Nash Crucible -- adversarial refinement")
        damages = {1: 0.340, 2: 0.080, 3: 0.020}
        ruff_c   = {1: 3, 2: 1, 3: 0}
        mypy_c   = {1: 2, 2: 0, 3: 0}
        bandit_c = {1: 1, 2: 0, 3: 0}
        _print_slow(f"          ruff: {ruff_c[cycle]} findings  |  mypy: {mypy_c[cycle]}  |  bandit: {bandit_c[cycle]}")
        _print_slow(f"          Damage score: {damages[cycle]:.3f}  (epsilon=0.05)")
        if cycle == 3:
            _print_slow("          >> Converged -- damage < epsilon.  Exiting crucible.")
        time.sleep(0.3)
        _print_slow("")

    # Phase 8 -- Verify
    _print_slow("[VERIFY]  Mechanical Oracle -- final grounding pass")
    _print_slow("          ruff .............. 0 violations")
    _print_slow("          mypy --strict ..... 0 errors")
    _print_slow("          bandit -lll ....... 0 HIGH findings")
    _print_slow("          pytest ............ 9/9 passed")
    _print_slow("          coverage .......... 94.2%")
    _print_slow("          complexity (radon)  A (avg 2.1)")
    _print_slow("")

    # Phase 9 -- Emit
    (output_dir / "lru_async.py").write_text(MOCK_LRU_CODE, encoding="utf-8")
    (output_dir / "test_lru_async.py").write_text(MOCK_TEST_CODE, encoding="utf-8")
    (output_dir / "BENCHMARKS.md").write_text(MOCK_BENCHMARKS, encoding="utf-8")

    _print_slow("[EMIT]    Hardened artifacts written to demo_output/")
    _print_slow("          +-- lru_async.py          (source)")
    _print_slow("          +-- test_lru_async.py     (adversarial tests)")
    _print_slow("          +-- BENCHMARKS.md         (performance report)")
    _print_slow("")
    _print_slow("=" * 62)
    _print_slow("  SAGE-PRO reasoning complete.  Nash equilibrium in 3 cycles.")
    _print_slow("=" * 62)


async def run_live_demo(task: str) -> None:
    """Run the real LangGraph pipeline (requires vLLM backends)."""
    # Only import heavy deps when actually needed
    from sage.core.graph import build_graph
    from sage.core.types import SageRequest

    output_dir = Path("demo_output")
    output_dir.mkdir(exist_ok=True)

    print("SAGE-PRO Reasoning Engine -- LIVE MODE")
    print("-" * 50)

    graph = build_graph()
    req = SageRequest(task=task, max_cycles=4)
    state = {"request": req, "repo_files": [], "xai_trace": []}

    result = await graph.ainvoke(state)

    final_code = result.get("final_code", "")
    final_tests = result.get("final_tests", "")

    (output_dir / "lru_async.py").write_text(final_code, encoding="utf-8")
    (output_dir / "test_lru_async.py").write_text(final_tests, encoding="utf-8")
    print("[EMIT]   Hardened artifact generated in demo_output/")


async def main() -> None:
    parser = argparse.ArgumentParser(description="SAGE-PRO Demo Runner")
    parser.add_argument(
        "--task", type=str,
        default="Build a thread-safe LRU cache with TTL and async eviction",
    )
    parser.add_argument(
        "--mock", action="store_true",
        help="Simulate the full pipeline locally without GPU backends",
    )
    args = parser.parse_args()

    if args.mock:
        await run_mock_demo(args.task)
    else:
        await run_live_demo(args.task)


if __name__ == "__main__":
    asyncio.run(main())
